mod app;
pub use app::*;
mod base;
pub use base::*;
mod header;
pub use header::*;
mod footer;
pub use footer::*;
mod home;
pub use home::*;
mod about;
pub use about::*;
mod page_not_found;
pub use page_not_found::*;
mod cats;
pub use cats::*;
mod cat_list;
pub use cat_list::*;
mod cat_detail;
pub use cat_detail::*;