mod app;
pub use app::*;
mod base;
pub use base::*;
mod header;
pub use header::*;
mod footer;
pub use footer::*;
mod home;
pub use home::*;
mod about;
pub use about::*;
mod page_not_found;
pub use page_not_found::*;
mod cats;
pub use cats::*;
mod cat_table;
pub use cat_table::*;
mod navbar;
pub use navbar::*;
mod cat_detail;
pub use cat_detail::*;
mod cat_create_form;
pub use cat_create_form::*;
mod input;
pub use input::*;
mod input_with_label;
pub use input_with_label::*;
mod button;
pub use button::*;
//
